### ISSUE TITLE
TFT Backlight is on after shutdown

### ISSUE THREAD

**Issue by tomek-szczesny** [hardkernel/smartpower3#2] opened 2021-10-30 23:11 UTC
Just noticed that. ;)

**Comment by leeseungcheol** [comment] 2021-11-03 01:52
Thank you for the issues.

But I can find the issue on my SmartPower3. When I long-press the menu/cancel button to enter shutdown mode, the backlight is off on my SP3.

Is there a case that the following code doesn't work?
[https://github.com/hardkernel/smartpower3/blob/master/smartpower3/screen.cpp#L171](url)

**Comment by tomek-szczesny** [comment] 2021-11-03 08:50
This is weird. I am pretty sure the backlight is on now, it's "glowing black" at me all the time. However the backlight is completely off while uploading new firmware, so probably there is no hardware issue.

I'll look into this after we're done with current measurements. :)

**Comment by cedel1** [comment] 2023-03-24 17:44
I can confirm the issue still exists. When SP3 is turned off, the backlight stays on at minimum brightness. So I can see why it would seem to be turned off for somebody that has higher brightness set.

The lines of code must have changed since then, but I can see where the problem is - will try to fix it.

**Comment by cedel1** [comment] 2023-03-25 02:29
Proposed solution in https://github.com/hardkernel/smartpower3/pull/25 .

**Comment by cedel1** [comment] 2023-04-03 12:41
Fixed in release 2.0 (https://wiki.odroid.com/accessory/power_supply_battery/smartpower3#apr03_v20).

**Closed as completed** 2023-04-04 02:51 UTC
